server {
    listen 80;

    # Обслуживание фронтенда (Expo Web)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Роутинг на сервис авторизации
    location /api/auth/ {
         Используем имя сервиса из твоего первого compose
        proxy_pass http://auth-dev:8000/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Роутинг на основной сервис
    #location /api/main/ {
        # Используем имя сервиса из твоего второго compose
        #proxy_pass http://fastapi_main_service:8000/;
        #proxy_set_header Host $host;
        #proxy_set_header X-Real-IP $remote_addr;
    #}
}
