server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 1. Добавляем поддержку типов файлов (чтобы браузер видел JS как JS)
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location / {
        # Сначала ищем файл, потом папку, если нет — отдаем index.html
        try_files $uri $uri/ /index.html;
    }

    # 2. Явно разрешаем доступ к папке _expo
    location /_expo/ {
        alias /usr/share/nginx/html/_expo/;
        # Отключаем лог для статики, чтобы не мусорить
        access_log off;
        # Кэшируем надолго
        expires max;
        add_header Cache-Control "public, no-transform";
        # Важно для дебага: если файла нет, выдать 404, а не index.html
        try_files $uri =404;
    }
}
