server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Важно: подгружаем типы файлов
    include /etc/nginx/mime.types;

    location / {
        # Стандарт для SPA: ищем файл, если нет — отдаем index.html
        try_files $uri $uri/ /index.html;
    }

    # Для статики Expo используем упрощенный root вместо alias
    location /_expo/ {
        # Просто ищем файл в корневой папке /usr/share/nginx/html/_expo/
        try_files $uri =404;
        access_log off;
        expires max;
        add_header Cache-Control "public, no-transform";
    }
}
